name: ppo_balancer
channels:
    - https://conda.anaconda.org/conda-forge
dependencies:
    - PyYAML >=6.0
    - gin-config >= 0.5.0
    - gymnasium >=0.28.1
    - loop-rate-limiters >=1.0.0
    - pip
    - stable-baselines3 >=2.1.0
    - upkie_description >=1.5.0
    - vulp >=2.2.1
    - pip:
        - upkie >=3.2.0
